# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7878679d40bbf797d2457aa0b61fa79a0c3bcc9538ee60b355612323df98dc7520d8ac745d781d3860b5f2de7d222b254dfbfedc5e0257c49f99d976d3adc1a

test:
  secret_key_base: e2ced7925040b71dc446f7b5f5f0c4097e39b209f051b5104e375a12fe2a98e34442b61546e1af4ddc733b135a7f61132429c018991cbf63cf38460979f9b420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
